Frontend/blueprint_data_manager.py
from flask import Blueprint, send_file, request, flash, redirect, render_template, url_for, jsonify
from Frontend.FlashMessageTypes import FlashMessageTypes
from Backend.interface import Interface
from Backend.backend_interface import BackendManager
from typing import Dict, Optional
from config.definitions import ROOT_DIR
import os

# Data files
CASE = "CASE.csv"
DIAGNOSIS = "DIAGNOSIS.csv"
LAB = "LAB.csv"
PERSON = "PERSON.csv"
PROCEDURE = "PROCEDURE.csv"

data_manager = Blueprint("data_manager", __name__)
upload_folder = os.path.join(ROOT_DIR, "upload")

config_path = os.path.join(ROOT_DIR, "config", "config.yml")
case_path = os.path.join(upload_folder, CASE)
diagnosis_path = os.path.join(upload_folder, DIAGNOSIS)
lab_path = os.path.join(upload_folder, LAB)
person_path = os.path.join(upload_folder, PERSON)
procedure_path = os.path.join(upload_folder, PROCEDURE)

case_head = ["CASE_ID", "PROVIDER_ID", "PATIENT_ID", "START_DATE", "END_DATE"]
diagnosis_head = ["PROVIDER_ID", "PATIENT_ID", "ADMISSION_NUMBER", "ADMISSION_DATE", "CLINICAL_STATUS", "ORPHA_CODE",
                  "ORPHA_TEXT", "ALPHAID_CODE", "ALPHAID_TEXT", "ICD_PRIMARY_CODE", "ICD_TEXT", "ICD_SECONDARY_CODE",
                  "DIAGNOSTIC_EXPLANATION", "ICD_VERSION", "ICD_MANIFESTATION", "DIAGNOSIS_TYPE"]
lab_head = ["IDENTIFIER", "STATUS", "CATEGORY", "PARAMETER_NAME", "PARAMETER_LOINC", "Patientidentifikator",
            "TEST_DATE", "NUMERIC_VALUE", "TEXTUAL_VALUE", "UNIT", "NORMAL_VALUES", "IS_NORMAL", "DEVIATION",
            "COMMENT", "UCUM_UNIT"]
lab_head_alt = ["IDENTIFIER", "STATUS", "CATEGORY", "PARAMETER_NAME", "PARAMETER_LOINC", "PATIENT_ID",
                "TEST_DATE", "NUMERIC_VALUE", "TEXTUAL_VALUE", "UNIT", "NORMAL_VALUES", "IS_NORMAL", "DEVIATION",
                "COMMENT", "UCUM_UNIT"]
person_head = ["PROVIDER_ID", "PATIENT_ID", "NAME", "FORNAME", "GENDER", "BIRTHDATE", "CITY", "ZIP", "DEATH",
               "DEATH_DATE", "DATE_OF_LIFE", "INSURANCE", "INSURANCE_ID"]
procedure_head = ["ID", "OPS_VERSION", "OPS_CODE", "PATIENT_ID", "EXECUTION_DATE"]

controller: Interface = BackendManager()


def check_existing_files() -> Dict[str, bool]:
    """
    check if all needed files are there

    :return: dict with name of the file followed by true if the file exists
    """
    if not os.path.isdir(upload_folder):
        os.mkdir(path=upload_folder)
    return {
        "config": True if os.path.isfile(config_path) else False,
        "case": True if os.path.isfile(case_path) else False,
        "diagnosis": True if os.path.isfile(diagnosis_path) else False,
        "lab": True if os.path.isfile(lab_path) else False,
        "person": True if os.path.isfile(person_path) else False,
        "procedure": True if os.path.isfile(procedure_path) else False,
    }


def clear_uploads() -> bool:
    """
    remove the csv files from the upload directory

    :return: true
    """
    print("clear data")
    for file in [case_path, diagnosis_path, lab_path, person_path, procedure_path]:
        if os.path.isfile(file):
            os.remove(file)
    return True


@data_manager.route("/etl")
def upload_page():
    """
    render the load_batch template
    """
    ex_f = check_existing_files()
    config_exists = ex_f["config"]
    del ex_f["config"]
    data_exists = all(ex_f.values())
    return render_template("load_batch.html",
                           paggename="Datensatz hinzufügen",
                           config_exists=config_exists,
                           data_exists=data_exists)


@data_manager.route("/etl/run", methods=["POST"])
def run_etl():
    """
    run the etl job
    """
    controller.reset_config()
    success = controller.run_etl(upload_folder)
    return jsonify({"success": success})


@data_manager.route('/etl/upload', methods=['POST'])
def upload_file():
    """
    handle files that are uploaded

    :return: success - the csv is correct; complete - all csvs are uploaded
    """
    success: bool = True
    complete: bool = True
    msg: str = ""

    try:
        key: str = request.form["key"]
        file = request.files["file"]
        path: Optional[str] = None
        check_list = None

        print(request.form)
        if request.form["uploads"] == '1':
            clear_uploads()
        print("data cleared")

        if key == "config":
            path = config_path
        elif key == "case":
            path = case_path
            check_list = case_head
        elif key == "diagnosis":
            path = diagnosis_path
            check_list = diagnosis_head
        elif key == "lab":
            path = lab_path
            check_list = lab_head
        elif key == "person":
            path = person_path
            check_list = person_head
        elif key == "procedure":
            path = procedure_path
            check_list = procedure_head

        file.save(path)

        if check_list is not None:
            with open(path) as f:
                actual_head = f.readline().strip().replace(" ", "").split(";")
                if set(check_list) != set(actual_head):
                    if key != 'lab' or set(lab_head_alt) != set(actual_head):
                        success = False
                        os.remove(path)
        print("check", success)

        complete = all(check_existing_files().values())

    except Exception as e:
        success = complete = False
        print(e)

    return jsonify({"success": success, "complete": complete})


@data_manager.route("/config")
def download_config():
    """
    download the config file
    """
    return send_file(config_path, as_attachment=True)


@data_manager.route("/reset_db")
def reset_db():
    """
    reset the database
    """
    if controller.reset_db():
        flash("Datenbank erfolgreich zurückgesetzt.", FlashMessageTypes.SUCCESS.value)
    else:
        flash("Datenbank konnte nicht zurückgesetzt werden.", FlashMessageTypes.FAILURE.value)
    return redirect(url_for("settings"))


@data_manager.route("/analysis/run", methods=['POST', 'GET'])
def analyse_data():
    """
    start the process which analyses the data in the db
    """
    success = controller.run_analysis()
    if request.method == 'POST':
        return jsonify({"success": success})
    else:
        if success:
            flash("Daten wurden erfolgreich analysiert.", FlashMessageTypes.SUCCESS.value)
        else:
            flash("Analyse der Daten ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for("settings"))

Frontend/blueprint_person.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from Backend.interface import PatientId, Interface, PatientData
from typing import Optional, Dict
from Backend.backend_interface import BackendManager
from Frontend.FlashMessageTypes import FlashMessageTypes
from datetime import date, datetime

import datetime

controller: Interface = BackendManager()

person_data = Blueprint("person_data", __name__)


@person_data.context_processor
def py_types() -> Dict[str, type]:
    """
    make some py-types accessible in the templates

    :return: types to use in the templates
    """
    return {
        "int": int,
        "bool": bool,
        "str": str,
        "float": float,
        "date": date
    }


@person_data.route("/")
def get_empty_patient_data():
    """
    generate empty patient data template

    :return: render the empty patient template
    """
    data = PatientData(birthdate=datetime.date.today(),
                       # Full name
                       name="",
                       hasCovid=False,
                       hasFever=False,
                       # Ausschlag auf der Haut
                       hasExanthem=False,
                       # Entzündung im Mundraum (Lippen, Zunge, Mundschleimhaut)
                       hasEnanthem=False,
                       # Geschwollene, gerötete Extremitäten
                       hasSwollenExtremeties=False,
                       # Bindehautentzündung
                       hasConjunctivitis=False,
                       # Geschwollene Lymphknoten
                       hasSwollenLymphnodes=False,
                       # Erbrechen, Übelkeit, Durchfall und/oder Bauchschmerzen
                       hasGastroIntestinalCondition=False,
                       # Perikardergüsse (Flüssigkeitsansammlung im Herzbeutel)
                       hasPericardialEffusions=False,
                       # Perikarditits (Herzbeutelentzündung)
                       hasPericarditis=False,
                       # Hat Myokarditis (Herzmuskelenzündung)
                       hasMyocarditis=False,
                       hasInflammationLab=False,
                       hasCoagulopathy=False,
                       hasKawasaki=False,
                       hasPims=False
                       )
    return render_template("person_data.html", patient_data=data, annotations=PatientData.__annotations__)


@person_data.route("/<int:patient_id>")
def get_patient_data(patient_id: PatientId):
    """
    get data for the patient with the given id

    :param patient_id:
    :return: render template with patient data
    """
    return render_template("person_data.html",
                           pagename="Patientendaten",
                           patient_id=patient_id,
                           patient_data=controller.get_patient_data(patient_id),
                           annotations=PatientData.__annotations__)


def get_patient_data_from_request() -> Optional[PatientData]:
    """
    extract the patient data from the request

    :return: None or the PatientData
    """
    patient_data: PatientData = {}
    for key, data_type in PatientData.__annotations__.items():
        if key in request.form:
            if data_type is bool:
                patient_data[key] = True
            elif data_type is date:
                patient_data[key] = datetime.datetime.strptime(request.form[key], "%Y-%m-%d")
            else:
                patient_data[key] = request.form[key]

        elif key not in request.form and data_type is bool:
            patient_data[key] = False

        else:
            return None
    return patient_data


@person_data.route("/save", methods=['POST'])
def add_patient_data():
    """
    add a new patient
    """
    patient_data = get_patient_data_from_request()

    if patient_data is None:
        flash("Hinzufügen eines neuen Patienten ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect("/")

    patient_id = controller.add_patient(patient_data)

    if patient_id:
        flash(f"Patient {patient_data['name']} wurde erfolgreich hinzugefügt.", FlashMessageTypes.SUCCESS.value)
        return redirect(url_for('.get_patient_data', patient_id=patient_id))
    else:
        flash(f"Hinzufügen des Patienten  {patient_data['name']} ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_empty_patient_data"))


@person_data.route("/<int:patient_id>/save", methods=['POST'])
def update_patient_data(patient_id: PatientId):
    """
    update data of an existing patient
    """
    patient_data = get_patient_data_from_request()

    if patient_data is None:
        flash(f"Aktualisieren eines Patienten mit der ID:({patient_id}) schlug fehl.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_patient_data", patient_id=patient_id))

    if controller.update_patient(patient_id, patient_data):
        flash(f"Patient {patient_data['name']} wurde erfolgreich aktualisiert.", FlashMessageTypes.SUCCESS.value)
        return redirect(url_for('.get_patient_data', patient_id=patient_id))
    else:
        flash(f"Aktualisieren eines Patienten (id: {patient_id}) {patient_data['name']} schlug fehl.",
              FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_patient_data", patient_id=patient_id))

Frontend/blueprint_results.py
from flask import Blueprint, render_template
from Backend.backend_interface import BackendManager
from Backend.interface import PatientId, Interface, DecisionReasons, Disease, PatientData

controller: Interface = BackendManager()

results = Blueprint("results", __name__)

# ToDO: generate PDF


@results.route("/all")
def get_analysis():
    """
    render analysis template
    """
    return render_template("analysis.html", pagename="Analyse", analysis_data=controller.analysis_data)


@results.route("/pims/<int:patient_id>")
def result_pims(patient_id: PatientId):
    """
    render the result template for the given patient and pims
    """
    return render_template("result.html",
                           pagename="Pims",
                           patient_id=patient_id,
                           decision_reason_data=controller.get_decision_reason(patient_id, Disease.PIMS),
                           decision_reason_annotations=DecisionReasons.__annotations__,
                           patient_data=controller.get_patient_data(patient_id),
                           annotations=PatientData.__annotations__)


@results.route("/kawasaki/<int:patient_id>")
def result_kawasaki(patient_id: PatientId):
    """
    render the result template for the given patient and kawasaki
    """
    return render_template("result.html",
                           pagename="Kawasaki",
                           patient_id=patient_id,
                           decision_reason_data=controller.get_decision_reason(patient_id, Disease.KAWASAKI),
                           decision_reason_annotations=DecisionReasons.__annotations__,
                           patient_data=controller.get_patient_data(patient_id),
                           annotations=PatientData.__annotations__)

Frontend/templates/Widgets/_flash_messages.html
<div id="flash_messages">

    <script type="text/javascript">
        $(document).ready(function(){
            $(".message_field").delay(400).slideDown("slow", "swing").delay(3000).fadeOut(1000, "swing");
        });
    </script>

    {% for category, msg in get_flashed_messages(with_categories=True) %}

        <div class="message_field {{ category }}">
            {{ msg }}
        </div>

    {% endfor %}

</div>

Frontend/templates/Widgets/_menu.html
<div id="menu">
    <div>
        <a class="btn menu_hm" href="{{ url_for('access_control.logout') }}">Logout</a>
        <a class="btn menu_hm" href="{{ url_for('main') }}">Daten</a>
    </div>
    <div>
        <div class="menu_hl1">Entscheidungsunterstützung</div>
        <div class="menu_hl2"></div>
    </div>
    <a class="btn menu_res" href="{{ url_for('results.get_analysis') }}">Analyse</a>

</div>

Frontend/templates/Widgets/_menu_left.html
<div id="left_menu">

    <a class="menu_entry pagename" href="{{ url_for('main') }}">
        <div class="icon">DS</div>
        <div class="full_name">{{ pagename }}</div>
    </a>

    {% if session["logged_in"] is defined and session["logged_in"] %}

        <!-- source: <div>Icons made by <a href="https://www.flaticon.com/authors/monkik" title="monkik">monkik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
        <a class="menu_entry" href="{{ url_for('results.get_analysis') }}">
            <div class="icon">
                <img src="{{ url_for('static', filename='Icons/data.png') }}" alt="Analyse">
            </div>
            <div class="full_name">Analyse</div>
        </a>

        <!-- source: <div>Icons made by <a href="https://icon54.com/" title="Pixel perfect">Pixel perfect</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
        <a class="menu_entry" href="{{ url_for('person_data.get_empty_patient_data') }}">
            <div class="icon">
                <img src="{{ url_for('static', filename='Icons/add_one.png') }}" alt="Person hinzufügen">
            </div>
            <div class="full_name">Person hinzufügen</div>
        </a>

        <!-- source: <div>Icons made by <a href="" title="Rizki Ahmad Fauzi">Rizki Ahmad Fauzi</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div> -->
        <a class="menu_entry" href="{{ url_for('data_manager.upload_page') }}">
            <div class="icon">
                <img src="{{ url_for('static', filename='Icons/add_multiple.png') }}" alt="Datensatz hinzufügen">
            </div>
            <div class="full_name">Datensatz hinzufügen</div>
        </a>

        <!-- source: <a href="https://www.flaticon.com/free-icons/download" title="download icons">Download icons created by Iconjam - Flaticon</a> -->
        {% if pagename == "Pims" or pagename == "Kawasaki" %}
        <a class="menu_entry" onclick="print()" onload="isResult()">
                <div class="icon">
                    <img src="{{ url_for('static', filename='Icons/pdf_download.png') }}" alt="Download als PDF">
                </div>
                <div  class="full_name">Download als PDF</div>
        </a>
        {% else %}
        <div class="small_filler">
            <div class="icon"></div>
            <div class="full_name"></div>
        </div>
        {% endif %}


        <div class="filler">
            <div class="icon"></div>
            <div class="full_name"></div>
        </div>


        <!-- source: <div>Icons erstellt von <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/de/" title="Flaticon">www.flaticon.com</a></div> -->
        <a class="menu_entry" href="{{ url_for('settings') }}">
            <div class="icon">
                <img src="{{ url_for('static', filename='Icons/settings.png') }}" alt="Einstellungen">
            </div>
            <div class="full_name">Einstellungen</div>
        </a>

        <!-- source: <div>Icons made by <a href="https://www.freepik.com" title="Freepik">Freepik</a> from <a href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a></div>-->
        <a class="menu_entry" href="{{ url_for('access_control.logout') }}">
            <div class="icon">
                <img src="{{ url_for('static', filename='Icons/logout.png') }}" alt="logout">
            </div>
            <div class="full_name">Logout</div>
        </a>
    {% else %}
        <div class="big_filler">
            <div class="icon"></div>
            <div class="full_name"></div>
        </div>
    {% endif %}

</div>

Frontend/templates/Widgets/_menu_top.html
<div id="menu">
    <div>
        <a class="btn menu_hm" href="{{ url_for('access_control.logout') }}">Logout</a>
        <a class="btn menu_hm" href="{{ url_for('main') }}">Daten</a>
    </div>
    <div>
        <div class="menu_hl1">Entscheidungsunterstützung</div>
        <div class="menu_hl2"></div>
    </div>
    <a class="btn menu_res" href="{{ url_for('results.get_analysis') }}">Analyse</a>

</div>

Frontend/templates/Widgets/_round_progress.html
<!-- Author: Kyle Shanks -->

<!-- <link href="https://fonts.googleapis.com/css?family=Droid+Sans+Mono" rel="stylesheet">
<link rel="prefetch" href="http://www.iconsdb.com/icons/preview/white/check-mark-xxl.png">
<link rel="prefetch" href="http://www.iconsdb.com/icons/preview/white/x-mark-xxl.png"> -->

<div class="container">
    <div class="abs-center front">
        <svg viewbox="0 0 80 80" class="abs-center rad-progress">
            <circle class="progress-background" cx="40" cy="40" r="35" />
            <circle class="progress-bar" cx="40" cy="40" r="35" stroke-dasharray="220" stroke-dashoffset="-220" />
            <div class="abs-center progress-label">0%</div>
        </svg>
    </div>
    <div class="abs-center back">
        <svg viewbox="0 0 80 80" class="abs-center alt-state">
            <circle class="progress_icon-background" cx="40" cy="40" r="35"  fill="#21cd92" stroke="#21cd92" stroke-width="8"/>
            <div class="abs-center progress_icon check"></div>
            <div class="abs-center progress_icon error"></div>
        </svg>
    </div>
</div>