Frontend/blueprint_data_manager.py
from flask import Blueprint, send_file, request, flash, redirect, render_template, url_for, jsonify
from Frontend.FlashMessageTypes import FlashMessageTypes
from Backend.interface import Interface
from Backend.backend_interface import BackendManager
from typing import Dict, Optional
from config.definitions import ROOT_DIR
import os

# Data files
CASE = "CASE.csv"
DIAGNOSIS = "DIAGNOSIS.csv"
LAB = "LAB.csv"
PERSON = "PERSON.csv"
PROCEDURE = "PROCEDURE.csv"

data_manager = Blueprint("data_manager", __name__)
upload_folder = os.path.join(ROOT_DIR, "upload")

config_path = os.path.join(ROOT_DIR, "config", "config.yml")
case_path = os.path.join(upload_folder, CASE)
diagnosis_path = os.path.join(upload_folder, DIAGNOSIS)
lab_path = os.path.join(upload_folder, LAB)
person_path = os.path.join(upload_folder, PERSON)
procedure_path = os.path.join(upload_folder, PROCEDURE)

case_head = ["CASE_ID", "PROVIDER_ID", "PATIENT_ID", "START_DATE", "END_DATE"]
diagnosis_head = ["PROVIDER_ID", "PATIENT_ID", "ADMISSION_NUMBER", "ADMISSION_DATE", "CLINICAL_STATUS", "ORPHA_CODE",
                  "ORPHA_TEXT", "ALPHAID_CODE", "ALPHAID_TEXT", "ICD_PRIMARY_CODE", "ICD_TEXT", "ICD_SECONDARY_CODE",
                  "DIAGNOSTIC_EXPLANATION", "ICD_VERSION", "ICD_MANIFESTATION", "DIAGNOSIS_TYPE"]
lab_head = ["IDENTIFIER", "STATUS", "CATEGORY", "PARAMETER_NAME", "PARAMETER_LOINC", "Patientidentifikator",
            "TEST_DATE", "NUMERIC_VALUE", "TEXTUAL_VALUE", "UNIT", "NORMAL_VALUES", "IS_NORMAL", "DEVIATION",
            "COMMENT", "UCUM_UNIT"]
lab_head_alt = ["IDENTIFIER", "STATUS", "CATEGORY", "PARAMETER_NAME", "PARAMETER_LOINC", "PATIENT_ID",
                "TEST_DATE", "NUMERIC_VALUE", "TEXTUAL_VALUE", "UNIT", "NORMAL_VALUES", "IS_NORMAL", "DEVIATION",
                "COMMENT", "UCUM_UNIT"]
person_head = ["PROVIDER_ID", "PATIENT_ID", "NAME", "FORNAME", "GENDER", "BIRTHDATE", "CITY", "ZIP", "DEATH",
               "DEATH_DATE", "DATE_OF_LIFE", "INSURANCE", "INSURANCE_ID"]
procedure_head = ["ID", "OPS_VERSION", "OPS_CODE", "PATIENT_ID", "EXECUTION_DATE"]

controller: Interface = BackendManager()


def check_existing_files() -> Dict[str, bool]:
    """
    check if all needed files are there

    :return: dict with name of the file followed by true if the file exists
    """
    if not os.path.isdir(upload_folder):
        os.mkdir(path=upload_folder)
    return {
        "config": True if os.path.isfile(config_path) else False,
        "case": True if os.path.isfile(case_path) else False,
        "diagnosis": True if os.path.isfile(diagnosis_path) else False,
        "lab": True if os.path.isfile(lab_path) else False,
        "person": True if os.path.isfile(person_path) else False,
        "procedure": True if os.path.isfile(procedure_path) else False,
    }


def clear_uploads() -> bool:
    """
    remove the csv files from the upload directory

    :return: true
    """
    print("clear data")
    for file in [case_path, diagnosis_path, lab_path, person_path, procedure_path]:
        if os.path.isfile(file):
            os.remove(file)
    return True


@data_manager.route("/etl")
def upload_page():
    """
    render the load_batch template
    """
    ex_f = check_existing_files()
    config_exists = ex_f["config"]
    del ex_f["config"]
    data_exists = all(ex_f.values())
    return render_template("load_batch.html",
                           paggename="Datensatz hinzufügen",
                           config_exists=config_exists,
                           data_exists=data_exists)


@data_manager.route("/etl/run", methods=["POST"])
def run_etl():
    """
    run the etl job
    """
    controller.reset_config()
    success = controller.run_etl(upload_folder)
    return jsonify({"success": success})


@data_manager.route('/etl/upload', methods=['POST'])
def upload_file():
    """
    handle files that are uploaded

    :return: success - the csv is correct; complete - all csvs are uploaded
    """
    success: bool = True
    complete: bool = True
    msg: str = ""

    try:
        key: str = request.form["key"]
        file = request.files["file"]
        path: Optional[str] = None
        check_list = None

        print(request.form)
        if request.form["uploads"] == '1':
            clear_uploads()
        print("data cleared")

        if key == "config":
            path = config_path
        elif key == "case":
            path = case_path
            check_list = case_head
        elif key == "diagnosis":
            path = diagnosis_path
            check_list = diagnosis_head
        elif key == "lab":
            path = lab_path
            check_list = lab_head
        elif key == "person":
            path = person_path
            check_list = person_head
        elif key == "procedure":
            path = procedure_path
            check_list = procedure_head

        file.save(path)

        if check_list is not None:
            with open(path) as f:
                actual_head = f.readline().strip().replace(" ", "").split(";")
                if set(check_list) != set(actual_head):
                    if key != 'lab' or set(lab_head_alt) != set(actual_head):
                        success = False
                        os.remove(path)
        print("check", success)

        complete = all(check_existing_files().values())

    except Exception as e:
        success = complete = False
        print(e)

    return jsonify({"success": success, "complete": complete})


@data_manager.route("/config")
def download_config():
    """
    download the config file
    """
    return send_file(config_path, as_attachment=True)


@data_manager.route("/reset_db")
def reset_db():
    """
    reset the database
    """
    if controller.reset_db():
        flash("Datenbank erfolgreich zurückgesetzt.", FlashMessageTypes.SUCCESS.value)
    else:
        flash("Datenbank konnte nicht zurückgesetzt werden.", FlashMessageTypes.FAILURE.value)
    return redirect(url_for("settings"))


@data_manager.route("/analysis/run", methods=['POST', 'GET'])
def analyse_data():
    """
    start the process which analyses the data in the db
    """
    success = controller.run_analysis()
    if request.method == 'POST':
        return jsonify({"success": success})
    else:
        if success:
            flash("Daten wurden erfolgreich analysiert.", FlashMessageTypes.SUCCESS.value)
        else:
            flash("Analyse der Daten ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for("settings"))

Frontend/blueprint_person.py
from flask import Blueprint, render_template, redirect, request, url_for, flash
from Backend.interface import PatientId, Interface, PatientData
from typing import Optional, Dict
from Backend.backend_interface import BackendManager
from Frontend.FlashMessageTypes import FlashMessageTypes
from datetime import date, datetime

import datetime

controller: Interface = BackendManager()

person_data = Blueprint("person_data", __name__)


@person_data.context_processor
def py_types() -> Dict[str, type]:
    """
    make some py-types accessible in the templates

    :return: types to use in the templates
    """
    return {
        "int": int,
        "bool": bool,
        "str": str,
        "float": float,
        "date": date
    }


@person_data.route("/")
def get_empty_patient_data():
    """
    generate empty patient data template

    :return: render the empty patient template
    """
    data = PatientData(birthdate=datetime.date.today(),
                       # Full name
                       name="",
                       hasCovid=False,
                       hasFever=False,
                       # Ausschlag auf der Haut
                       hasExanthem=False,
                       # Entzündung im Mundraum (Lippen, Zunge, Mundschleimhaut)
                       hasEnanthem=False,
                       # Geschwollene, gerötete Extremitäten
                       hasSwollenExtremeties=False,
                       # Bindehautentzündung
                       hasConjunctivitis=False,
                       # Geschwollene Lymphknoten
                       hasSwollenLymphnodes=False,
                       # Erbrechen, Übelkeit, Durchfall und/oder Bauchschmerzen
                       hasGastroIntestinalCondition=False,
                       # Perikardergüsse (Flüssigkeitsansammlung im Herzbeutel)
                       hasPericardialEffusions=False,
                       # Perikarditits (Herzbeutelentzündung)
                       hasPericarditis=False,
                       # Hat Myokarditis (Herzmuskelenzündung)
                       hasMyocarditis=False,
                       hasInflammationLab=False,
                       hasCoagulopathy=False,
                       hasKawasaki=False,
                       hasPims=False
                       )
    return render_template("person_data.html", patient_data=data, annotations=PatientData.__annotations__)


@person_data.route("/<int:patient_id>")
def get_patient_data(patient_id: PatientId):
    """
    get data for the patient with the given id

    :param patient_id:
    :return: render template with patient data
    """
    return render_template("person_data.html",
                           pagename="Patientendaten",
                           patient_id=patient_id,
                           patient_data=controller.get_patient_data(patient_id),
                           annotations=PatientData.__annotations__)


def get_patient_data_from_request() -> Optional[PatientData]:
    """
    extract the patient data from the request

    :return: None or the PatientData
    """
    patient_data: PatientData = {}
    for key, data_type in PatientData.__annotations__.items():
        if key in request.form:
            if data_type is bool:
                patient_data[key] = True
            elif data_type is date:
                patient_data[key] = datetime.datetime.strptime(request.form[key], "%Y-%m-%d")
            else:
                patient_data[key] = request.form[key]

        elif key not in request.form and data_type is bool:
            patient_data[key] = False

        else:
            return None
    return patient_data


@person_data.route("/save", methods=['POST'])
def add_patient_data():
    """
    add a new patient
    """
    patient_data = get_patient_data_from_request()

    if patient_data is None:
        flash("Hinzufügen eines neuen Patienten ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect("/")

    patient_id = controller.add_patient(patient_data)

    if patient_id:
        flash(f"Patient {patient_data['name']} wurde erfolgreich hinzugefügt.", FlashMessageTypes.SUCCESS.value)
        return redirect(url_for('.get_patient_data', patient_id=patient_id))
    else:
        flash(f"Hinzufügen des Patienten  {patient_data['name']} ist fehlgeschlagen.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_empty_patient_data"))


@person_data.route("/<int:patient_id>/save", methods=['POST'])
def update_patient_data(patient_id: PatientId):
    """
    update data of an existing patient
    """
    patient_data = get_patient_data_from_request()

    if patient_data is None:
        flash(f"Aktualisieren eines Patienten mit der ID:({patient_id}) schlug fehl.", FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_patient_data", patient_id=patient_id))

    if controller.update_patient(patient_id, patient_data):
        flash(f"Patient {patient_data['name']} wurde erfolgreich aktualisiert.", FlashMessageTypes.SUCCESS.value)
        return redirect(url_for('.get_patient_data', patient_id=patient_id))
    else:
        flash(f"Aktualisieren eines Patienten (id: {patient_id}) {patient_data['name']} schlug fehl.",
              FlashMessageTypes.FAILURE.value)
        return redirect(url_for(".get_patient_data", patient_id=patient_id))

Frontend/templates/load_batch.html
{% extends "Layout/layout.html" %}
{% from "Macros/_progressbar.html" import progressbar %}
{% from "Macros/_upload_field.html" import upload_file %}

{% block stylesheets %}
    <link rel = "stylesheet" type = "text/css" href = "{{ url_for('static', filename='CSS/load_batch.css') }}">
{% endblock %}

{% block title %}
    Upload
{% endblock %}

{% block java_script %}
  <script type="text/javascript">
    var uploads = 0;

    $(document).ready(function(){
      $("#run_etl").hide();
      $("#upload_data").hide();
      $(".upload_progress").hide();
      $("#upload_config").show();
      $("#step_config").addClass("in-progress");

      registerActionListener();
    });
  
  /**
  * set all action listener
  * @function registerActionListener
  */
  function registerActionListener(){

    // control flow

    // config
    $("#skip_upload_config, #config_uploaded").click((event) => finished_config($(event.target)));

    // data upload
    $("#skip_upload_data, #data_uploaded").click((event) => finished_upload($(event.target)));

    // etl
    $("#finish_btn").click((event) => {
      $("#finish_btn").hide();
      $("#finish_progress").show();
      var id = "finish_progress";
      var failure = false;
      //$(".progress-bar").css("transition-duration", "60s");
      //update_progress(id, 49);
      var interval = interval_upload_progress(id, 0, 70, 1000);

      // etl
      $.ajax({
        url: "{{ url_for('data_manager.run_etl') }}",
        type: 'post',
        //data: fd,
        contentType: false,
        processData: false,
        success: function(response){
          if(response.success){
            clearInterval(interval);
            update_progress(id, 70);

            // analyse data
            interval = interval_upload_progress(id, 71, 99, 500);
            $.ajax({
              url: "{{ url_for('data_manager.analyse_data') }}",
              type: 'post',
              //data: fd,
              contentType: false,
              processData: false,
              success: function(response){
                clearInterval(interval);;
                if(response.success){
                  update_progress(id, 100);
                  $("#step_etl").removeClass("in-progress")
                                  .addClass("complete");
                  
                }else if (response.msg){
                  error(id);
                  // TODO: display msg
                }
                else{
                  error(id);
                }},
              error: function(response){
                clearInterval(interval);
                error(id)
                console.log(response.statusText);
                // TODO: display msg
              },
            });
            
          }else if (response.msg){
            clearInterval(interval);
            error(id);
            // TODO: display msg
            failure = true;
          }
          else{
            clearInterval(interval);
            error(id);
            failure = true;
          }},
        error: function(response){
          clearInterval(interval);
          error(id)
          console.log(response.statusText);
          // TODO: display msg
          failure = true
          
        },
      });
    });


    // file upload handling
    $('.drop_zone').on('dragover', function(event) {
      event.preventDefault();
      event.stopPropagation();
    });

    $(".drop_zone").on("dragenter", function(event){
      event.preventDefault();
      event.stopPropagation();
      $(event.target).addClass("in_drop_zone");
    });

    $("body").on("dragenter", function(event){
      event.preventDefault();
      event.stopPropagation();
      $(".in_drop_zone").removeClass("in_drop_zone");
    });


    $(".drop_zone").on("drop", function(event){
      event.preventDefault();
      event.stopPropagation();
      $(".in_drop_zone").removeClass("in_drop_zone");
      var file = null;

      if (event.originalEvent.dataTransfer.items && event.originalEvent.dataTransfer.items[0].kind === 'file') {
        file = event.originalEvent.dataTransfer.items[0].getAsFile();
      } else if(event.originalEvent.dataTransfer.files.length > 0) {
        // Use DataTransfer interface to access the file(s)
        file = event.originalEvent.dataTransfer.files[0]
      }

      var id = "";
      var target = $(event.target);
      while (!target.is("body")){
        if (target.hasClass('drop_zone')){
          id = target[0].id;
          break;
        } else {
          target = target.parent();
        }
      }
      
      if (file != null && id != ""){
        var url = "{{ url_for('data_manager.upload_file') }}";

        upload_file(url, id, file);
      }

    });
  }

  /**
  * config is finished
  * @function finished_config
  * @param {Object} target - that is clicked on
  */
  function finished_config(target){
    if (!target.hasClass("disabled")){
      $("#upload_config").hide();
      $("#run_etl").hide();
      $("#upload_data").show();
      $("#step_config").removeClass("in-progress")
                       .addClass("complete");
      $("#step_data").addClass("in-progress");
    }
  }

  /**
  * data upload is finished
  * @function finished_upload
  * @param {Object} target - that is clicked on
  */
  function finished_upload(target){
    if (!target.hasClass("disabled")){
      $("#upload_config").hide();
      $("#upload_data").hide();
      $("#run_etl").show();
      $("#step_data").removeClass("in-progress")
                     .addClass("complete");
      $("#step_etl").addClass("in-progress");
    }
  }

  /**
  * file upload finished - handel bg logic
  * @function upload_file_finished
  * @param {string} id - of the drop_zone
  * @param {boolean} success - of the upload
  * @param {boolean} complete - the upload of all necessary files
  */
  function upload_file_finished(id, success, complete){

    if (id == "config" && success){
      $("#" + id).removeClass("failed");
      $("#" + id).addClass("complet");
      $("#skip_upload_config").addClass("disabled");
      $("#config_uploaded").removeClass("disabled");
    } else if (success){
      $("#" + id).removeClass("failed");
      $("#" + id).addClass("complet");

      // check if all files are there
      if (complete){
        $("#data_uploaded").removeClass("disabled");
      } else {
        $("#skip_upload_data").addClass("disabled");
        $("#data_uploaded").addClass("disabled");
      }

    } else {
      $("#" + id).removeClass("complet");
      $("#" + id).addClass("failed");
      $("#skip_upload_data").addClass("disabled");
      $("#data_uploaded").addClass("disabled");
    }

  }

  /**
  * upload the given file and controll progress bar
  * @function upload_file
  * @param {string} target_url - the file should be send to
  * @param {string} id - of the drop_zone
  * @param {Object} file - that should be uploaded
  */
  function upload_file(target_url, id, file){

    // fake a progress bar
    $("#"+id + " .upload_empty").hide();
    $("#"+id + " .upload_progress").show();
    update_progress(id, 10);
    if (id != "config"){uploads++};
    var interval = interval_upload_progress(id, 0, 99, 3);

    var fd = new FormData();
    fd.append('key', id);
    fd.append('uploads', uploads);
    fd.append('file', file);
    var complete = false

    $.ajax({
      url: target_url,
      type: 'post',
      data: fd,
      contentType: false,
      processData: false,
      success: function(response){
        clearInterval(interval);
        complete = response.complete;
        if(response.success){
          update_progress(id, 100);
          upload_file_finished(id, true, complete);
          
        }else if (response.msg){
          error(id);
          upload_file_finished(id, false, complete);
          // TODO: display msg
        }
        else{
          error(id);
          upload_file_finished(id, false, complete);
        }},
      error: function(response){
        clearInterval(interval);
        error(id)
        console.log(response.statusText);
        upload_file_finished(id, false, complete);
        // TODO: display msg
      },
    });
  }

  /**
  * update the round progress bar stepwise
  * @function interval_upload_progress
  * @param {string} id - of the drop_zone
  * @param {int} start_pct - the counter should start
  * @param {int} target_pct - the counter should reache
  * @param {int} time_per_step - before the pct is increased (by 1) again in ms
  * @return {Object} interval
  */
  function interval_upload_progress(id, start_pct, target_pct, time_per_step){
    $("#"+id+" .progress-bar").css("transition-duration", time_per_step / 1000+"s");
    var i = start_pct;
    interval = setInterval(() => {
      if (i < target_pct){
        update_progress(id, ++i);
      } else {
        clearInterval(interval);
      }
      
    }, time_per_step);
    return interval;
  }

  /**
  * update the round progress bar
  * @function update_progress
  * @param {string} id - of the drop_zone
  * @param {int} pct - the upload is complete
  */
  function update_progress(id, pct) {
    if(!isNaN(pct) && pct != null) {
      if(pct > 100) {pct = 100}; // Too High
      if(pct < 0) {pct = 0};     // Too Low
      var offset = (( -parseFloat(pct) /100) * 220) - 220; // Getting offset for the SVG
  
      $("#"+id+' .progress-bar').attr('stroke-dashoffset',offset);
      $("#"+id+' .progress-label').text(Number(Math.round(pct+'e2')+'e-2')+'%'); // Rounds to two decimal places

      // Check for finish
      (pct === 100)?( complete(id) ):( incomplete(id) );
    };
      
  };

  // Complete and Error States
  function complete(id) { $("#"+id+' .container').addClass('flipped complete').removeClass('error'); };
  function incomplete(id) { $("#"+id+' .container').removeClass('flipped complete'); };
  function error(id) { $("#"+id+' .container').addClass('flipped error').removeClass('complete');  };
  function no_error(id) { $("#"+id+' .container').removeClass('flipped error'); };
  
</script>

{% endblock %}

{% block content %}

  {{ progressbar(step_config="Konfiguration hochladen",
                 step_data="Daten hochladen",
                 step_etl="ETL starten") }}

  

  <div id="upload_config">
    {% if config_exists %}
      <a id="skip_upload_config" class="btn">Existierende Konfigurationsdatei verwenden</a>
    {% endif %}
    {{ upload_file("config", "config.yml") }}
    <a id="config_uploaded" class="btn half_right disabled">weiter</a>
  </div>

  <div id="upload_data">
    {% if data_exists %}
      <a id="skip_upload_data" class="btn">Existierende Daten verwenden</a>
    {% endif %}
    {{ upload_file("case", "CASE.csv") }}
    {{ upload_file("diagnosis", "DIAGNOSIS.csv") }}
    {{ upload_file("lab", "LAB.csv") }}
    {{ upload_file("person", "PERSON.csv") }}
    {{ upload_file("procedure", "PROCEDURE.csv") }}
    <a id="data_uploaded" class="btn half_right disabled">weiter</a>
  </div>

  <div id="run_etl">
    <a id="finish_btn" class="btn">Start</a>
    <div id="finish_progress" class="upload_progress">
      {% include "Widgets/_round_progress.html" %}
  </div>
  </div>

{% endblock %}

Frontend/templates/main.html
{% extends "Layout/layout.html" %}

{% block stylesheets %}
    <link rel = "stylesheet" type = "text/css" href = "{{ url_for('static', filename='CSS/main.css') }}">
{% endblock %}


{% block title %}
    Startseite
{% endblock %}
<!-- TODO: rework -->

{% block content %}
    <div class="grid_table_entry disclaimer">
    <p>
        Willkommen im Webclient des Entscheidungsunterst&uuml;tzungssystems für das <strong>Kawasaki-Syndrom</strong>
        und <strong>PIMS</strong> (Paediatric inflammatory multisystem syndrome).
        <br/>
        Diese Anwendung soll medizinisches Fachpersonal hinsichtlich der Diagnose der oben genannten Krankheiten
        unterst&uuml;tzen. Das System kann genutzt werden, um eine Wahrscheinlichkeit der Erkrankung für einzelne
        Patienten zu bestimmen. Es ist aber auch m&ouml;glich eine Analyse für Gruppen von Patienten durchzuf&uuml;hren,
         in dem entsprechende Datentabellen hier hochgeladen werden.
        <br/>
        Beachten Sie, dass die hier berechneten Ergebnisse ohne Gew&auml;hr zu verstehen sind. S&auml;mtliche Ergebnisse
        m&uuml;ssen durch medizinisches Fachpersonal auf ihre Richtigkeit &uuml;berpr&uuml;ft werden.
    </p>
    </div>


    <a href="{{ url_for('person_data.get_empty_patient_data') }}" class="btn grid_table_entry">
            Patient anlegen
    </a>

    <a href="{{ url_for('data_manager.upload_page') }}" class="btn grid_table_entry">
            Datensatz hinzuf&uuml;gen
    </a>
    
    <a href="{{ url_for('data_manager.reset_db') }}" class="btn grid_table_entry">
            Datenbank zur&uuml;cksetzen
    </a>

{% endblock %}

Frontend/templates/settings.html
{% extends "Layout/layout.html" %}

{% block stylesheets %}
    <link rel = "stylesheet" type = "text/css" href = "{{ url_for('static', filename='CSS/settings.css') }}">
{% endblock %}


{% block title %}
    Einstellungen
{% endblock %}

{% block java_script %}
    {% set hue = analysis_color['hue'] %}
    {% set saturation = analysis_color['saturation'] %}
    {% set lightness = analysis_color['lightness'] %}
    <script type="text/javascript">
        
        var hue = {{ analysis_color['hue'] }};  
        var saturation = {{ analysis_color['saturation'] }};
        var lightness = {{ analysis_color['lightness'] }};

        
        $(document).ready(function(){
            $("#color_pic").hide();
            $("#reset_db").hide();
            setColor(hue, saturation, lightness);
            colorBar(hue, saturation, lightness);

            $("#hue").on("input", (event) => {
                hue = event.target.value;
                colorBar(hue, saturation, lightness);
            });

            $("#saturation").on("input", (event) => {
                saturation = event.target.value;
                colorBar(hue, saturation, lightness);
            });

            $("#lightness").on("input", (event) => {
                lightness = event.target.value;
                colorBar(hue, saturation, lightness);
            });

            $(".cancel").click(() => {
                console.log("cancel");
                $("#color_pic").hide();
                $("#reset_db").hide();
                $("#settings").show();
            });

            $("#btn_reset_db").click(() => {
                $("#color_pic").hide();
                $("#settings").hide();
                $("#reset_db").show();
            });

            $("#btn_select_color").click(() => {
                
                $("#settings").hide();
                $("#reset_db").hide();
                $("#color_pic").show();

                setColor(hue, saturation, lightness);
                colorBar(hue, saturation, lightness);
            });

            $("#set_color").click(() => {
                $.post("{{ url_for('set_color') }}", {
                    "hue": hue,
                    "saturation": saturation,
                    "lightness": lightness
                }, () => {
                    $("#color_pic").hide();
                    $("#reset_db").hide();
                    $("#settings").show();
                });
            });

        });

        function colorBar(hue, saturation, lightness){
            $("#color_100").css("background-color", "hsla("+hue+", "+saturation+"%, "+lightness+"%, 100%)");
            $("#color_75").css("background-color", "hsla("+hue+", "+saturation+"%, "+lightness+"%, 75%)");
            $("#color_50").css("background-color", "hsla("+hue+", "+saturation+"%, "+lightness+"%, 50%)");
            $("#color_0").css("background-color", "hsla("+hue+", "+saturation+"%, "+lightness+"%, 0%)");
        }

        function setColor(hue, saturation, lightness){
            $("#hue").val(hue);
            $("#saturation").val(saturation);
            $("#lightness").val(lightness);
        }

    </script>
{% endblock %}

{% block content %}

    <div id="settings">

        <a href="{{ url_for('data_manager.download_config') }}" class="btn">
            Konfigurationsdatei herunterladen
        </a>

        <a {% if not db_empty %} href="{{ url_for('data_manager.analyse_data') }}" {% endif %} class="btn  {% if db_empty %} disabled {% endif %}">
            Analyse neustarten
        </a>

        <a {% if not db_empty %} id="btn_reset_db" {% endif %} class="btn  {% if db_empty %} disabled {% endif %}">
            Datenbank zurücksetzen
        </a>

        <a id="btn_select_color" class="btn">
            Warnfarbe für Erkrankungen wählen
        </a>
    </div>

    <div id="color_pic">
        <div class="disclaimer">
            Die gewählte Farbe wird verwendet um die Wahrscheinlichkeit einer Erkrankung mit Pims oder Kawasaki darzustellen.         
        </div>

        <div id="color_bar">
            <div id="color_100">{{ translation_kawasaki[1.0] }}</div>
            <div id="color_75">{{ translation_kawasaki[0.75] }}</div>
            <div id="color_50">{{ translation_kawasaki[0.5] }}</div>
            <div id="color_0">{{ translation_kawasaki[0.0] }}</div>
        </div>

        <div class="box">
            <div class="range">
                <label for="hue">Farbton:</label>
                <input type="range" id="hue" class="range_input" name="hue" min=0 max=360 />
            </div>

            <div class="range">
                <label for="saturation">Sättigung:</label>
                <input type="range" id="saturation" class="range_input" name="saturation" min=0 max=100 />
            </div>

            <div class="range">
                <label for="lightness">Helligkeit:</label>
                <input type="range" id="lightness" class="range_input" name="lightness" min=0 max=100 />
            </div>
        </div>

        <div class="on_line">
            <a class="cancel btn cancle short_btn">Abbrechen</a>
            <a id="set_color" class="btn continue short_btn">Speichern</a>
        </div>

    </div>

    <div id="reset_db">
        <div class="disclaimer">
            Alle Daten gehen verloren! Sind Sie sicher das Sie die Datenbank zurücksetzen wollen?
            
        </div>
        <div class="on_line">
            <a class="cancel btn short_btn">Abbrechen</a>
            <a id="reseting_db" class="btn short_btn" href="{{ url_for('data_manager.reset_db') }}">Zurücksetzen</a>
        </div>
        

    </div>

{% endblock %}